#logging file
logging: 
  file: D:/zwl/logs/turbine/turbine.log
  
#turbine
turbine:
  appConfig: TEST-SERVICE
  clusterNameExpression: new String("default")
  instanceUrlSuffix: manage/hystrix.stream