#database
compact:
  password: false
spring: 
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/zwl
    username: cpmdb
    password: pcpmdb
    ons:
      configuration: none
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    
    #hibernate
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

#logging
logging: 
  config: src/main/resources/logback-spring.xml
  level: 
    root: INFO
    com.ch.myr: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
#enable showdown service by http and disable shutdown validation 
endpoints: 
  shutdown:
    enabled: true
    sensitive: false 

#management endpoint path and endpoint allow ip
management:
  context-path: /manage
  address: 127.0.0.1

#eureka  
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
  
  #register management port
  instance: 
    metadata-map:
      management.port: ${management.port:8081}

#hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
        timeout:
          enabled: true
        semaphore:
          maxConcurrentRequests: 200
  threadpool:
    default:
      coreSize: 50
      allowMaximumSizeToDivergeFromCoreSize: true
      maximumSize: 200

#ribbon
ribbon: 
  ReadTimeout: 30000
  ConnectTimeout: 1000
#
##zuul
#zuul: 
#  host:
#    #starting the connection 
#    connect-timeout-millis: 60000
#    
#    #monitor the continuous incoming data flow
#    socket-timeout-millis: 60000
         